/**
 * Permission Matrix for RBAC (Role-Based Access Control)
 * Define all permissions for the entire application here
 */

export const PERMISSIONS = {
  // Leads Module
  LEADS_VIEW: 'LEADS_VIEW',
  LEADS_CREATE: 'LEADS_CREATE',
  LEADS_EDIT: 'LEADS_EDIT',
  LEADS_DELETE: 'LEADS_DELETE',
  LEADS_EXPORT: 'LEADS_EXPORT',
  LEADS_IMPORT: 'LEADS_IMPORT',
  LEADS_ASSIGN: 'LEADS_ASSIGN',
  
  // Customers Module
  CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
  CUSTOMERS_CREATE: 'CUSTOMERS_CREATE',
  CUSTOMERS_EDIT: 'CUSTOMERS_EDIT',
  CUSTOMERS_DELETE: 'CUSTOMERS_DELETE',
  CUSTOMERS_EXPORT: 'CUSTOMERS_EXPORT',
  
  // Projects Module
  PROJECTS_VIEW: 'PROJECTS_VIEW',
  PROJECTS_CREATE: 'PROJECTS_CREATE',
  PROJECTS_EDIT: 'PROJECTS_EDIT',
  PROJECTS_DELETE: 'PROJECTS_DELETE',
  PROJECTS_ASSIGN: 'PROJECTS_ASSIGN',
  
  // Inventory Module
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_CREATE: 'INVENTORY_CREATE',
  INVENTORY_EDIT: 'INVENTORY_EDIT',
  INVENTORY_DELETE: 'INVENTORY_DELETE',
  INVENTORY_APPROVE: 'INVENTORY_APPROVE',
  
  // Finance Module
  FINANCE_VIEW: 'FINANCE_VIEW',
  FINANCE_CREATE_INVOICE: 'FINANCE_CREATE_INVOICE',
  FINANCE_EDIT_INVOICE: 'FINANCE_EDIT_INVOICE',
  FINANCE_DELETE_INVOICE: 'FINANCE_DELETE_INVOICE',
  FINANCE_RECORD_PAYMENT: 'FINANCE_RECORD_PAYMENT',
  FINANCE_APPROVE_EXPENSE: 'FINANCE_APPROVE_EXPENSE',
  
  // Design Module
  DESIGN_VIEW: 'DESIGN_VIEW',
  DESIGN_CREATE: 'DESIGN_CREATE',
  DESIGN_EDIT: 'DESIGN_EDIT',
  DESIGN_APPROVE: 'DESIGN_APPROVE',
  
  // Documents Module
  DOCUMENTS_VIEW: 'DOCUMENTS_VIEW',
  DOCUMENTS_CREATE: 'DOCUMENTS_CREATE',
  DOCUMENTS_EDIT: 'DOCUMENTS_EDIT',
  DOCUMENTS_DELETE: 'DOCUMENTS_DELETE',
  DOCUMENTS_SEND: 'DOCUMENTS_SEND',
  DOCUMENTS_APPROVE: 'DOCUMENTS_APPROVE',
  DOCUMENTS_EXPORT: 'DOCUMENTS_EXPORT',
  DOCUMENTS_CONVERT: 'DOCUMENTS_CONVERT',
  DOCUMENTS_VERSION: 'DOCUMENTS_VERSION',
  DOCUMENTS_TEMPLATE_MANAGE: 'DOCUMENTS_TEMPLATE_MANAGE',
  
  // Users & Roles
  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_EDIT: 'USERS_EDIT',
  USERS_DELETE: 'USERS_DELETE',
  ROLES_MANAGE: 'ROLES_MANAGE',
  
  // Settings
  SETTINGS_VIEW: 'SETTINGS_VIEW',
  SETTINGS_EDIT: 'SETTINGS_EDIT',
  
  // Audit & Backup
  AUDIT_LOGS_VIEW: 'AUDIT_LOGS_VIEW',
  BACKUP_MANAGE: 'BACKUP_MANAGE',
  
  // Super Admin
  SUPER_ADMIN_ACCESS: 'SUPER_ADMIN_ACCESS',
  TENANTS_MANAGE: 'TENANTS_MANAGE',
  SUBSCRIPTIONS_MANAGE: 'SUBSCRIPTIONS_MANAGE',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * Role-based permission groups
 */
export const ROLE_PERMISSIONS = {
  owner: Object.values(PERMISSIONS), // All permissions
  
  admin: [
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.LEADS_DELETE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],
  
  employee: [
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
  ],
} as const;

/**
 * Check if user has permission
 */
export function hasPermission(
  userPermissions: string[],
  requiredPermission: Permission
): boolean {
  return userPermissions.includes(requiredPermission);
}

/**
 * Check if user has any of the permissions
 */
export function hasAnyPermission(
  userPermissions: string[],
  requiredPermissions: Permission[]
): boolean {
  return requiredPermissions.some(perm => userPermissions.includes(perm));
}
