import jsPDF from 'jspdf';
import { CompanyDetails, DashboardExportData } from '@/features/dashboard/types/pdf';

export class CoverPageGenerator {
  private doc: jsPDF;
  private companyDetails: CompanyDetails;
  private dashboardData: DashboardExportData;

  constructor(doc: jsPDF, companyDetails: CompanyDetails, dashboardData: DashboardExportData) {
    this.doc = doc;
    this.companyDetails = companyDetails;
    this.dashboardData = dashboardData;
  }

  async generate(): Promise<void> {
    // Add decorative background elements
    this.addDecorativeElements();
    
    // Add logo
    await this.addLogo();
    
    // Add title and subtitle
    this.addTitleSection();
    
    // Add metadata
    this.addMetadata();
    
    // Add KPI summary cards
    this.addKPISummaryCards();
    
    // Add footer
    this.addFooter();
  }

  private addDecorativeElements(): void {
    const primaryColor = this.companyDetails.brandingColors.primary;
    const secondaryColor = this.companyDetails.brandingColors.secondary;
    
    // Top accent bar
    this.doc.setFillColor(...primaryColor);
    this.doc.rect(0, 0, 210, 8, 'F');
    
    // Bottom accent bar
    this.doc.setFillColor(...primaryColor);
    this.doc.rect(0, 287, 210, 10, 'F');
    
    // Side accent bar
    this.doc.setFillColor(...secondaryColor);
    this.doc.rect(0, 0, 5, 297, 'F');
  }

  private async addLogo(): Promise<void> {
    if (this.companyDetails.logo) {
      this.doc.addImage(this.companyDetails.logo, 'PNG', 20, 25, 40, 40);
    } else {
      // Placeholder for logo
      this.doc.setFillColor(...this.companyDetails.brandingColors.secondary);
      this.doc.roundedRect(20, 25, 40, 40, 3, 3, 'F');
      this.doc.setTextColor(255, 255, 255);
      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text('LOGO', 40, 45, { align: 'center' });
    }
    
    // Add company name next to logo
    this.doc.setTextColor(0, 0, 0);
    this.doc.setFontSize(18);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(this.companyDetails.name, 70, 45);
    
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(this.companyDetails.address, 70, 52);
    this.doc.text(`Phone: ${this.companyDetails.phone}`, 70, 57);
    this.doc.text(`Email: ${this.companyDetails.email}`, 70, 62);
    
    // Add GST and CIN
    this.doc.setFontSize(8);
    this.doc.setTextColor(80, 80, 80);
    this.doc.text(`GST: ${this.companyDetails.gst}`, 70, 67);
    this.doc.text(`CIN: ${this.companyDetails.cin}`, 70, 72);
  }

  private addTitleSection(): void {
    const primaryColor = this.companyDetails.brandingColors.primary;
    
    // Main title
    this.doc.setTextColor(...primaryColor);
    this.doc.setFontSize(32);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Executive Dashboard', 20, 95);
    
    // Subtitle
    this.doc.setTextColor(80, 80, 80);
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text('Business Operations Report', 20, 108);
    
    // Divider line
    this.doc.setDrawColor(...primaryColor);
    this.doc.setLineWidth(1);
    this.doc.line(20, 115, 190, 115);
  }

  private addMetadata(): void {
    this.doc.setTextColor(60, 60, 60);
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    
    const metadata = [
      { label: 'Report Period:', value: this.formatFilter(this.dashboardData.filter) },
      { label: 'Generated By:', value: this.dashboardData.generatedBy },
      { label: 'Generated On:', value: new Date().toLocaleString() },
      { label: 'Report Version:', value: this.dashboardData.exportVersion },
    ];
    
    let y = 130;
    metadata.forEach((item) => {
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(item.label, 20, y);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(item.value, 80, y);
      y += 12;
    });
  }

  private addKPISummaryCards(): void {
    const primaryColor = this.companyDetails.brandingColors.primary;
    const accentColor = this.companyDetails.brandingColors.accent;
    
    const kpis = [
      { label: 'Total Revenue', value: this.dashboardData.kpis.revenue, change: this.dashboardData.kpis.revenueChange },
      { label: 'Active Leads', value: String(this.dashboardData.kpis.leads), change: this.dashboardData.kpis.leadsChange },
      { label: 'Active Projects', value: String(this.dashboardData.kpis.activeProjects), change: this.dashboardData.kpis.projectsChange },
      { label: 'Total Customers', value: String(this.dashboardData.kpis.customers), change: this.dashboardData.kpis.customersChange },
    ];
    
    const cardWidth = 85;
    const cardHeight = 35;
    const startX = 20;
    const startY = 185;
    const gap = 10;
    
    kpis.forEach((kpi, i) => {
      const x = startX + (i % 2) * (cardWidth + gap);
      const y = startY + Math.floor(i / 2) * (cardHeight + gap);
      
      // Card background
      this.doc.setFillColor(245, 245, 245);
      this.doc.roundedRect(x, y, cardWidth, cardHeight, 2, 2, 'F');
      
      // Card border
      this.doc.setDrawColor(...primaryColor);
      this.doc.setLineWidth(0.5);
      this.doc.roundedRect(x, y, cardWidth, cardHeight, 2, 2, 'S');
      
      // Label
      this.doc.setTextColor(100, 100, 100);
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(kpi.label, x + 5, y + 10);
      
      // Value
      this.doc.setTextColor(...primaryColor);
      this.doc.setFontSize(14);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(kpi.value, x + 5, y + 20);
      
      // Change indicator
      const isPositive = kpi.change.startsWith('+');
      this.doc.setTextColor(isPositive ? 34 : 231, isPositive ? 139 : 76, 34); // Green or red
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(kpi.change, x + 5, y + 28);
    });
  }

  private addFooter(): void {
    const primaryColor = this.companyDetails.brandingColors.primary;
    
    this.doc.setTextColor(255, 255, 255);
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    
    this.doc.text('Confidential Document', 105, 293, { align: 'center' });
    this.doc.text(this.companyDetails.website, 105, 298, { align: 'center' });
  }

  private formatFilter(filter: string): string {
    const filterMap: Record<string, string> = {
      'today': 'Today',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'last_month': 'Last Month',
      'this_quarter': 'This Quarter',
      'last_quarter': 'Last Quarter',
      'this_year': 'This Year',
      'last_year': 'Last Year',
      'all_time': 'All Time',
    };
    return filterMap[filter] || filter;
  }
}
